#!/usr/bin/env bash
# Displays the content of the current directory:
# In a list format
# Where only the part of the name after the first dash is displayed

for item in *; do
	echo "$item" | cut -d '-' -f 2
done
